apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-data
  labels:
    type: local
spec:
  storageClassName:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: datadir-rocketchat-mongodb-primary-0
  hostPath:
    path: "/mnt/rocketchat/data"